title: Home Assistant

background: center / cover no-repeat url("/local/back.jpg") fixed

resources:

# Get Card-Mod to make background transparent.  Great powerful module
# available here:  https://github.com/thomasloven/lovelace-card-mod

  - url: /local/js/card-mod.js?v=0.11
    type: module
    

#  Add this line to reference color lite card.  Copy the .js file to the path below in your config dir
  - url: /local/js/color-lite-card.js?v=0.348
    type: js
    
    


views:
        
  - path: floorplan
    title: Main Floor
    background: "#000000"  
    panel: true    
    cards:
      - type: picture-elements
        image: /local/floorplan/house.jpg  
        
    #   use card-mod to remove card background with CSS
        
        style: |
          ha-card {          
          background: none;          
          }

          
          
        elements:
                  
          - type: custom:color-lite-card
            entity: light.living_room_lamp   
            image:
              /local/floorplan/LRLamp.png?v=2   
            color_image:
              /local/floorplan/LRLampColor.png                            
            style:
              top: 50%
              left: 50%
              width: 100%  


    